class EventUser < ActiveRecord::Base
# link table between User and Event - autogenerated created_at field is iso8601 timestamp
# EventUser.created_at meets the requirements of the Timestamp field in the project description
   belongs_to :event
   belongs_to :user
end